#!/bin/bash
# Credits: @mrismanaziz
# Copyright (C) 2022 Pyro-ManUserbot
#
# This file is a part of < https://github.com/mrismanaziz/PyroMan-Userbot/ >
# PLease read the GNU Affero General Public License in
# <https://www.github.com/mrismanaziz/PyroMan-Userbot/blob/main/LICENSE/>.
#
# t.me/SharingUserbot & t.me/Lunatic0de

_starter () {
    echo "Downloading source code"
    git clone https://github.com/AyiinXd/AyinUbot
    cd AyinUbot/ && rm -rf .git
    python3 ../updater.py ../requirements.txt ../requirements.txt
    echo "AyiinXd version - 0.1.0, Copyright © 2022 (Ayiin) <https://github.com/AyiinXd>"
    python3 -m AyiinXd
}

_starter